/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ObraIdRouteImport } from './routes/obra.$id'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'
import { Route as AdminObraIdRouteImport } from './routes/admin.obra.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ObraIdRoute = ObraIdRouteImport.update({
  id: '/obra/$id',
  path: '/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminObraIdRoute = AdminObraIdRouteImport.update({
  id: '/admin/obra/$id',
  path: '/admin/obra/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/conta': typeof ContaRoute
  '/galeria': typeof GaleriaRoute
  '/obra/$id': typeof ObraIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/obra/$id': typeof AdminObraIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/conta': typeof ContaRoute
  '/galeria': typeof GaleriaRoute
  '/obra/$id': typeof ObraIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/obra/$id': typeof AdminObraIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/conta': typeof ContaRoute
  '/galeria': typeof GaleriaRoute
  '/obra/$id': typeof ObraIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/obra/$id': typeof AdminObraIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/conta'
    | '/galeria'
    | '/obra/$id'
    | '/perfil/$id'
    | '/admin/'
    | '/admin/obra/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/conta'
    | '/galeria'
    | '/obra/$id'
    | '/perfil/$id'
    | '/admin'
    | '/admin/obra/$id'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/conta'
    | '/galeria'
    | '/obra/$id'
    | '/perfil/$id'
    | '/admin/'
    | '/admin/obra/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ContaRoute: typeof ContaRoute
  GaleriaRoute: typeof GaleriaRoute
  ObraIdRoute: typeof ObraIdRoute
  PerfilIdRoute: typeof PerfilIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminObraIdRoute: typeof AdminObraIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obra/$id': {
      id: '/obra/$id'
      path: '/obra/$id'
      fullPath: '/obra/$id'
      preLoaderRoute: typeof ObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/obra/$id': {
      id: '/admin/obra/$id'
      path: '/admin/obra/$id'
      fullPath: '/admin/obra/$id'
      preLoaderRoute: typeof AdminObraIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ContaRoute: ContaRoute,
  GaleriaRoute: GaleriaRoute,
  ObraIdRoute: ObraIdRoute,
  PerfilIdRoute: PerfilIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminObraIdRoute: AdminObraIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
