// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/arts": {
            "get": {
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pagination.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/art.artResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "description": "Dados da Arte",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/art.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/art.artResponse"
                        }
                    }
                }
            }
        },
        "/arts/{id}": {
            "get": {
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Arte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/art.artResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Arte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Arte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos para atualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/art.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/arts/{id}/likes": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Arte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Arts"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Arte",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/contents": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Contents"
                ],
                "parameters": [
                    {
                        "description": "Lista de Atualizações com IDs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/content.updateItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/contents/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Contents"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Conteúdo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/favorites": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Favorites"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Favorite"
                            }
                        }
                    }
                }
            }
        },
        "/favorites/{title_id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Favorites"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "title_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Favorites"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "title_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/genres": {
            "get": {
                "tags": [
                    "Genres"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Genre"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Genres"
                ],
                "parameters": [
                    {
                        "description": "Lista de Gêneros a cadastrar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/genre.createItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Genre"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Genres"
                ],
                "parameters": [
                    {
                        "description": "Lista de Gêneros a atualizar com seus IDs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/genre.updateItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/genres/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Genres"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Gênero",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profiles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Profiles"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Profile"
                            }
                        }
                    }
                }
            }
        },
        "/profiles/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Profiles"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Profile"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Profiles"
                ],
                "parameters": [
                    {
                        "description": "Campos para atualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profiles/{id}": {
            "get": {
                "tags": [
                    "Profiles"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do Perfil",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Profile"
                        }
                    }
                }
            }
        },
        "/profiles/{id}/favorites": {
            "get": {
                "tags": [
                    "Favorites"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do Perfil",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Favorite"
                            }
                        }
                    }
                }
            }
        },
        "/profiles/{id}/role": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Profiles"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do Perfil",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo cargo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/profile.updateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/titles": {
            "get": {
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filtrar por tipo (anime, manga, novel)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Número da página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Itens por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/pagination.Result"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/domain.Title"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "description": "Dados da Obra",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/title.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Title"
                        }
                    }
                }
            }
        },
        "/titles/{id}": {
            "get": {
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Title"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos para atualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/title.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Title"
                        }
                    }
                }
            }
        },
        "/titles/{title_id}/contents": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Contents"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "title_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lista de Conteúdos a criar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/content.createItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Content"
                            }
                        }
                    }
                }
            }
        },
        "/upload/arts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Storage"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "Imagem da Arte",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/upload/novels": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Storage"
                ],
                "parameters": [
                    {
                        "type": "file",
                        "description": "Arquivo da Novel (PDF/EPUB)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "art.artResponse": {
            "type": "object",
            "properties": {
                "author": {
                    "$ref": "#/definitions/art.authorResponse"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "likes_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "art.authorResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "art.createRequest": {
            "type": "object",
            "required": [
                "image_url",
                "title"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Deu muito trabalho!"
                },
                "image_url": {
                    "type": "string",
                    "example": "https://exemplo.com/arte.jpg"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2,
                    "example": "Fanart do Goku"
                }
            }
        },
        "art.updateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                }
            }
        },
        "content.createItem": {
            "type": "object",
            "required": [
                "language",
                "source_url",
                "title"
            ],
            "properties": {
                "cover_url": {
                    "type": "string",
                    "example": "https://exemplo.com/capa-vol1.jpg"
                },
                "episode": {
                    "type": "number",
                    "example": 1
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "sub",
                        "dub",
                        "none"
                    ],
                    "example": "sub"
                },
                "season": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1
                },
                "source_url": {
                    "type": "string",
                    "example": "https://stream.exemplo.com/ep1.mp4"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2,
                    "example": "Episódio 1 - O Despertar"
                }
            }
        },
        "content.updateItem": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "episode": {
                    "type": "number"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "sub",
                        "dub",
                        "none"
                    ]
                },
                "season": {
                    "type": "integer"
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                }
            }
        },
        "domain.Art": {
            "type": "object",
            "required": [
                "image_url",
                "profile_id",
                "title"
            ],
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image_url": {
                    "type": "string"
                },
                "likes_count": {
                    "type": "integer"
                },
                "profile": {
                    "$ref": "#/definitions/domain.Profile"
                },
                "profile_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                }
            }
        },
        "domain.Content": {
            "type": "object",
            "required": [
                "language",
                "source_url",
                "title",
                "title_id"
            ],
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "episode": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "sub",
                        "dub",
                        "none"
                    ]
                },
                "season": {
                    "type": "integer",
                    "minimum": 0
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "title_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Favorite": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "profile_id": {
                    "type": "string"
                },
                "title": {
                    "$ref": "#/definitions/domain.Title"
                },
                "title_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Genre": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "titles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Title"
                    }
                }
            }
        },
        "domain.Profile": {
            "type": "object",
            "required": [
                "email",
                "id",
                "role",
                "username"
            ],
            "properties": {
                "arts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Art"
                    }
                },
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "favorites": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Favorite"
                    }
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "moderator",
                        "content_manager",
                        "admin"
                    ]
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                }
            }
        },
        "domain.Title": {
            "type": "object",
            "required": [
                "age_rating",
                "cover_url",
                "name",
                "publication_year",
                "status",
                "type"
            ],
            "properties": {
                "age_rating": {
                    "type": "string",
                    "enum": [
                        "L",
                        "12",
                        "14",
                        "16",
                        "18"
                    ]
                },
                "banner_url": {
                    "type": "string"
                },
                "contents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Content"
                    }
                },
                "cover_url": {
                    "type": "string"
                },
                "episode_count": {
                    "type": "integer"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Genre"
                    }
                },
                "has_dub": {
                    "type": "boolean"
                },
                "has_sub": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "publication_year": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "releasing",
                        "completed"
                    ]
                },
                "synopsis": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "anime",
                        "manga",
                        "novel"
                    ]
                }
            }
        },
        "genre.createItem": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Isekai"
                }
            }
        },
        "genre.updateItem": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Ação"
                }
            }
        },
        "pagination.Result": {
            "type": "object",
            "properties": {
                "data": {},
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "profile.updateRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 4
                }
            }
        },
        "profile.updateRoleRequest": {
            "type": "object",
            "required": [
                "role"
            ],
            "properties": {
                "role": {
                    "type": "string",
                    "enum": [
                        "user",
                        "moderator",
                        "content_manager",
                        "admin"
                    ],
                    "example": "moderator"
                }
            }
        },
        "title.createRequest": {
            "type": "object",
            "required": [
                "age_rating",
                "cover_url",
                "name",
                "publication_year",
                "status",
                "type"
            ],
            "properties": {
                "age_rating": {
                    "type": "string",
                    "enum": [
                        "L",
                        "12",
                        "14",
                        "16",
                        "18"
                    ],
                    "example": "16"
                },
                "banner_url": {
                    "type": "string",
                    "example": "https://exemplo.com/banner.jpg"
                },
                "cover_url": {
                    "type": "string",
                    "example": "https://exemplo.com/capa.jpg"
                },
                "genre_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2,
                    "example": "Solo Leveling"
                },
                "publication_year": {
                    "type": "integer",
                    "example": 2024
                },
                "source": {
                    "type": "string",
                    "example": "ID000001"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "releasing",
                        "completed"
                    ],
                    "example": "releasing"
                },
                "synopsis": {
                    "type": "string",
                    "example": "O caçador mais fraco do mundo..."
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "anime",
                        "manga",
                        "novel"
                    ],
                    "example": "anime"
                }
            }
        },
        "title.updateRequest": {
            "type": "object",
            "properties": {
                "age_rating": {
                    "type": "string",
                    "enum": [
                        "L",
                        "12",
                        "14",
                        "16",
                        "18"
                    ]
                },
                "banner_url": {
                    "type": "string"
                },
                "cover_url": {
                    "type": "string"
                },
                "genre_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "publication_year": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "releasing",
                        "completed"
                    ]
                },
                "synopsis": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "anime",
                        "manga",
                        "novel"
                    ]
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GeekVerse API",
	Description:      "API central da plataforma GeekVerse (Streaming, Leitura e Galeria de Artes).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
