// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contents": {
            "patch": {
                "tags": [
                    "Contents"
                ],
                "parameters": [
                    {
                        "description": "Lista de Atualizações com IDs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/content.updateItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/contents/{id}": {
            "delete": {
                "tags": [
                    "Contents"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Conteúdo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/genres": {
            "get": {
                "tags": [
                    "Genres"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Genre"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Genres"
                ],
                "parameters": [
                    {
                        "description": "Lista de Gêneros a cadastrar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/genre.createItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Genre"
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Genres"
                ],
                "parameters": [
                    {
                        "description": "Lista de Gêneros a atualizar com seus IDs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/genre.updateItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/genres/{id}": {
            "delete": {
                "tags": [
                    "Genres"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID do Gênero",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/titles": {
            "get": {
                "tags": [
                    "Titles"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Title"
                            }
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "description": "Dados da Obra",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/title.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Title"
                        }
                    }
                }
            }
        },
        "/titles/{id}": {
            "get": {
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Title"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "tags": [
                    "Titles"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Campos para atualizar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/title.updateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Title"
                        }
                    }
                }
            }
        },
        "/titles/{title_id}/contents": {
            "post": {
                "tags": [
                    "Contents"
                ],
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Obra",
                        "name": "title_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lista de Conteúdos a criar",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/content.createItem"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Content"
                            }
                        }
                    }
                }
            }
        },
        "/upload/{bucket}": {
            "post": {
                "tags": [
                    "Storage"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome do Balde (novels ou arts)",
                        "name": "bucket",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Arquivo a enviar",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "content.createItem": {
            "type": "object",
            "required": [
                "language",
                "source_url",
                "title"
            ],
            "properties": {
                "cover_url": {
                    "type": "string",
                    "example": "https://exemplo.com/capa-vol1.jpg"
                },
                "episode": {
                    "type": "number",
                    "example": 1
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "sub",
                        "dub",
                        "none"
                    ],
                    "example": "sub"
                },
                "season": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 1
                },
                "source_url": {
                    "type": "string",
                    "example": "https://stream.exemplo.com/ep1.mp4"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2,
                    "example": "Episódio 1 - O Despertar"
                }
            }
        },
        "content.updateItem": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "episode": {
                    "type": "number"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "sub",
                        "dub",
                        "none"
                    ]
                },
                "season": {
                    "type": "integer"
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                }
            }
        },
        "domain.Content": {
            "type": "object",
            "required": [
                "language",
                "source_url",
                "title",
                "title_id"
            ],
            "properties": {
                "cover_url": {
                    "type": "string"
                },
                "episode": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "language": {
                    "type": "string",
                    "enum": [
                        "sub",
                        "dub",
                        "none"
                    ]
                },
                "season": {
                    "type": "integer",
                    "minimum": 0
                },
                "source_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "title_id": {
                    "type": "integer"
                }
            }
        },
        "domain.Genre": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2
                },
                "titles": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Title"
                    }
                }
            }
        },
        "domain.Title": {
            "type": "object",
            "required": [
                "age_rating",
                "cover_url",
                "name",
                "publication_year",
                "status",
                "type"
            ],
            "properties": {
                "age_rating": {
                    "type": "string",
                    "enum": [
                        "L",
                        "12",
                        "14",
                        "16",
                        "18"
                    ]
                },
                "banner_url": {
                    "type": "string"
                },
                "contents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Content"
                    }
                },
                "cover_url": {
                    "type": "string"
                },
                "genres": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Genre"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "publication_year": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "releasing",
                        "completed"
                    ]
                },
                "synopsis": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "anime",
                        "manga",
                        "novel"
                    ]
                }
            }
        },
        "genre.createItem": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Isekai"
                }
            }
        },
        "genre.updateItem": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 2,
                    "example": "Ação"
                }
            }
        },
        "title.createRequest": {
            "type": "object"
        },
        "title.updateRequest": {
            "type": "object",
            "properties": {
                "age_rating": {
                    "type": "string",
                    "enum": [
                        "L",
                        "12",
                        "14",
                        "16",
                        "18"
                    ]
                },
                "banner_url": {
                    "type": "string"
                },
                "cover_url": {
                    "type": "string"
                },
                "genre_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string",
                    "maxLength": 150,
                    "minLength": 2
                },
                "publication_year": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "releasing",
                        "completed"
                    ]
                },
                "synopsis": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "anime",
                        "manga",
                        "novel"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GeekVerse API",
	Description:      "API central da plataforma GeekVerse (Streaming, Leitura e Galeria de Artes).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
