basePath: /
definitions:
  content.createItem:
    properties:
      cover_url:
        example: https://exemplo.com/capa-vol1.jpg
        type: string
      episode:
        example: 1
        type: number
      language:
        enum:
        - sub
        - dub
        - none
        example: sub
        type: string
      season:
        example: 1
        minimum: 0
        type: integer
      source_url:
        example: https://stream.exemplo.com/ep1.mp4
        type: string
      title:
        example: Episódio 1 - O Despertar
        maxLength: 150
        minLength: 2
        type: string
    required:
    - language
    - source_url
    - title
    type: object
  content.updateItem:
    properties:
      cover_url:
        type: string
      episode:
        type: number
      id:
        example: 1
        type: integer
      language:
        enum:
        - sub
        - dub
        - none
        type: string
      season:
        type: integer
      source_url:
        type: string
      title:
        maxLength: 150
        minLength: 2
        type: string
    required:
    - id
    type: object
  domain.Content:
    properties:
      cover_url:
        type: string
      episode:
        type: number
      id:
        type: integer
      language:
        enum:
        - sub
        - dub
        - none
        type: string
      season:
        minimum: 0
        type: integer
      source_url:
        type: string
      title:
        maxLength: 150
        minLength: 2
        type: string
      title_id:
        type: integer
    required:
    - language
    - source_url
    - title
    - title_id
    type: object
  domain.Genre:
    properties:
      id:
        type: integer
      name:
        maxLength: 50
        minLength: 2
        type: string
      titles:
        items:
          $ref: '#/definitions/domain.Title'
        type: array
    required:
    - name
    type: object
  domain.Title:
    properties:
      age_rating:
        enum:
        - L
        - "12"
        - "14"
        - "16"
        - "18"
        type: string
      banner_url:
        type: string
      contents:
        items:
          $ref: '#/definitions/domain.Content'
        type: array
      cover_url:
        type: string
      genres:
        items:
          $ref: '#/definitions/domain.Genre'
        type: array
      id:
        type: integer
      name:
        maxLength: 150
        minLength: 2
        type: string
      publication_year:
        type: integer
      source:
        type: string
      status:
        enum:
        - releasing
        - completed
        type: string
      synopsis:
        type: string
      type:
        enum:
        - anime
        - manga
        - novel
        type: string
    required:
    - age_rating
    - cover_url
    - name
    - publication_year
    - status
    - type
    type: object
  genre.createItem:
    properties:
      name:
        example: Isekai
        maxLength: 50
        minLength: 2
        type: string
    required:
    - name
    type: object
  genre.updateItem:
    properties:
      id:
        example: 1
        type: integer
      name:
        example: Ação
        maxLength: 50
        minLength: 2
        type: string
    required:
    - id
    - name
    type: object
  title.createRequest:
    type: object
  title.updateRequest:
    properties:
      age_rating:
        enum:
        - L
        - "12"
        - "14"
        - "16"
        - "18"
        type: string
      banner_url:
        type: string
      cover_url:
        type: string
      genre_ids:
        items:
          type: integer
        type: array
      name:
        maxLength: 150
        minLength: 2
        type: string
      publication_year:
        type: integer
      source:
        type: string
      status:
        enum:
        - releasing
        - completed
        type: string
      synopsis:
        type: string
      type:
        enum:
        - anime
        - manga
        - novel
        type: string
    type: object
info:
  contact: {}
  description: API central da plataforma GeekVerse (Streaming, Leitura e Galeria de
    Artes).
  title: GeekVerse API
  version: "1.0"
paths:
  /contents:
    patch:
      parameters:
      - description: Lista de Atualizações com IDs
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/content.updateItem'
          type: array
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Contents
  /contents/{id}:
    delete:
      parameters:
      - description: ID do Conteúdo
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Contents
  /genres:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Genre'
            type: array
      tags:
      - Genres
    patch:
      parameters:
      - description: Lista de Gêneros a atualizar com seus IDs
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/genre.updateItem'
          type: array
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Genres
    post:
      parameters:
      - description: Lista de Gêneros a cadastrar
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/genre.createItem'
          type: array
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/domain.Genre'
            type: array
      tags:
      - Genres
  /genres/{id}:
    delete:
      parameters:
      - description: ID do Gênero
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Genres
  /titles:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Title'
            type: array
      tags:
      - Titles
    post:
      parameters:
      - description: Dados da Obra
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/title.createRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.Title'
      tags:
      - Titles
  /titles/{id}:
    delete:
      parameters:
      - description: ID da Obra
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Titles
    get:
      parameters:
      - description: ID da Obra
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Title'
      tags:
      - Titles
    patch:
      parameters:
      - description: ID da Obra
        in: path
        name: id
        required: true
        type: integer
      - description: Campos para atualizar
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/title.updateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Title'
      tags:
      - Titles
  /titles/{title_id}/contents:
    post:
      parameters:
      - description: ID da Obra
        in: path
        name: title_id
        required: true
        type: integer
      - description: Lista de Conteúdos a criar
        in: body
        name: request
        required: true
        schema:
          items:
            $ref: '#/definitions/content.createItem'
          type: array
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/domain.Content'
            type: array
      tags:
      - Contents
  /upload/{bucket}:
    post:
      parameters:
      - description: Nome do Balde (novels ou arts)
        in: path
        name: bucket
        required: true
        type: string
      - description: Arquivo a enviar
        in: formData
        name: file
        required: true
        type: file
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - Storage
swagger: "2.0"
